---
title: "Pollen_Microbe"
output: html_document
---
```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(lubridate)
library(shiny)
```

#pollen_micriobe dataset
```{r}
pollen_micriobe<-read_csv("C:/Users/jenny/OneDrive/桌面/BIS15L_W2026_Group1/Nectar bacteria stimulate pollen germination/doi_10_25338_B8BS75__v20210727/pollen_microbe_data.csv")%>%
  clean_names()
```

```{r}
glimpse(pollen_micriobe)
```
```{r}
summary(pollen_micriobe)
```

#distribution of microbe group
```{r}
pollen_micriobe %>%
  ggplot(aes(x=microbe_group, fill=microbe_group))+
  geom_bar()+
  theme_minimal()+
  labs(
    title = "Distribution of Microbe Groups",
    x="Microbe Group",
    y="Count")+
  theme(axis.text.x=element_text(angle=45, hjust=1))
```

#microbe group and all germination
```{r}
pollen_micriobe%>%
  ggplot(aes(x=microbe_group, y=allgerm, fill=microbe_group))+
  geom_boxplot()+
  facet_wrap(~timepoint)+
  theme_minimal()+
  labs(
    title="All Germination of Different Microbe Group by Timepoints",
    x="Microbe Group",
    y="All Germination")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

#microbe group and all germination(distribution)
```{r}
pollen_micriobe%>%
  ggplot(aes(x = prop_germ))+
  geom_histogram(
    binwidth = 0.05,
    fill = "lightblue",
    color = "black")+
  theme_minimal()+
  facet_wrap(~microbe_group)+
  labs(
    title="Distribution of Proportion Germinated",
    x="Proportion Germinated",
    y="Count")
```

#microbe group and all  burst
```{r}
pollen_micriobe%>%
  ggplot(aes(x=microbe_group, y=allburst, fill=microbe_group))+
  geom_boxplot()+
  facet_wrap(~timepoint)+
  theme_minimal()+
  labs(
    title="All Burst of Different Microbe Group by Timepoints",
    x="Microbe Group",
    y="All Burst")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

#microbe group and all germination(distribution)
```{r}
pollen_micriobe%>%
  ggplot(aes(x=prop_burst))+
  geom_histogram(
    binwidth = 0.05,
    fill = "lightblue",
    color = "black")+
  theme_minimal()+
  facet_wrap(~microbe_group)+
  labs(
    title="Distribution of Proportion Burst",
    x="Proportion Burst",
    y="Count")
```

#germination and time
```{r}
pollen_micriobe%>%
  group_by(microbe_group, timepoint)%>%
  summarize(mean_germ = mean(prop_germ, na.rm = TRUE)) %>%
  ggplot(aes(x=timepoint, 
             y=mean_germ, 
             color=microbe_group))+
  geom_line()+
  geom_point()+
  theme_minimal()+
  labs(
    title="Mean Germination Over Time for Each Microbe Group",
    x="Timepoint",
    y="Mean Proportion Germinated",
    color="Microbe Group")
```

#standard OD & all germination
```{r}
pollen_micriobe %>%
  ggplot(aes(x=factor(standardized_od_plate), y=allgerm, fill=microbe_group)) +
  geom_boxplot()+
  theme_minimal()+
  facet_wrap(~timepoint)+
  labs(
    title="Effect of OD on Germination",
    x="Initial OD",
    y="All Germination")
```

